services:
  db:
    image: mysql
    container_name: mysql-opinarte
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - exercicio:/var/lib/mysql

volumes:
  exercicio: